### ISSUE TITLE
.txt and .npy file required

### ISSUE THREAD

**Issue by kmanjari** [lsaiml/CaVINet#3]
I did not find any .txt and .npy file in your dataset that has been used in program. Can you please help me with this?

**Comment by pvskand** [comment]
Sorry for the delay in responding. I have uploaded `.txt` files. By tonight I will be uploading the script to convert the `.txt` files to `.npy` files. Thanks for being patient.

**Comment by pjh1023** [comment]
The identity list you uploaded seems to be in .txt file where as the program is expecting an .npy file.
Can you upload the .npy file?

**Comment by iszhyang** [comment]
> Sorry for the delay in responding. I have uploaded `.txt` files. By tonight I will be uploading the script to convert the `.txt` files to `.npy` files. Thanks for being patient.

Thank you for sharing your work. I want to reproduce your work on my computer. Could you please upload the txt and npy files as soon as possible?Thank you!

**Comment by ckngithub** [comment]
We will upload it at the earliest. Please pardon the delay.
