### ISSUE TITLE
Lacking rcmalli_vggface_tf_vgg16.h5

### ISSUE THREAD

**Issue by Becomebright** [lsaiml/CaVINet#7]
On Line 214 of train.py: 
`model.load_weights(
        'untied_softmax_weighted_error_33_33_33_lagmul_0.2_aug.h5')`
I can not find this file. Could you please upload it?

**Comment by pvskand** [comment]
Actually, for training, you don't need this file. You can comment the line and run the code. But you would need VGG-Face pretrained weights, and hence have to install https://github.com/rcmalli/keras-vggface. Let me know if you face any other problems.

**Comment by Becomebright** [comment]
Thanks for your reply. It helps me a lot.
